apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: jtan22/petclinic-mysql-minikube:1.0.0
          resources:
            limits:
              memory: 1024Mi
              cpu: "2"
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100